global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-app'
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['tharseo-backend-v2.onrender.com:80']
