global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: 'nestjs'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['https://tharseo-backend-v2.onrender.com']  
      # - targets: ['localhost:3000'] 
