global:
  scrape_interval: 60s

remote_write:
  - url: https://prometheus-prod-40-prod-sa-east-1.grafana.net/api/prom/push
    basic_auth:
      username: ${GRAFANA_USERNAME}
      password: ${GRAFANA_PASSWORD}

scrape_configs:
  - job_name: nestjs
    metrics_path: '/metrics'
    static_configs:
      - targets: ["tharseo-backend-v2.onrender.com:80"]