global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-app-metrics'
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['tharseo.zapto.org:80']

  - job_name: 'nestjs-health-check'
    scrape_interval: 15s
    metrics_path: '/health/check'  
    static_configs:
      - targets: ['tharseo.zapto.org:80']
